version: '3'

services:
  app:
    build: . 
    container_name: rede-social
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "4002:80"
    environment:
      MYSQL_USER_DB: redesocial
      MYSQL_USER_PASS: 123
      MYSQL_ADMIN_PASS: 123